### ISSUE TITLE
Placement of cursor

### ISSUE THREAD

**Issue by alphaone** [irohiroki/RubyBlockConverter#1]
Hi,

I really like your plugin. It will be very helpful within my workflow.

There is one minor issue with the placement of the cursor after the conversion from curly braces to do-end. The cursor will be after the "end". I think it would make much more sense if the cursor would be placed at the end of the last line of the body.

There is no problem the other way around. The cursor is placed before the closing brace.

**Comment by irohiroki** [comment]
Thanks for your feedback! I got your point. I totally agree with you.
I'll see how it can be fixed.

**Comment by irohiroki** [comment]
see #2.
