### ISSUE TITLE
Bug in parser

### ISSUE THREAD

**Issue by fappelman** [irohiroki/RubyBlockConverter#11]
I have noticed a problem in the parser that I would like to report.

I have the following piece of dummy code:

``` Ruby
class Dummy

  def do_start(req,resp)
p @@jobs
    raise ParseException.new 403, "busy" if @@busy
  end

  def cleanup_thread
    begin
      Thread.new do
        begin
          # Loop over all the elements in the @@jobs array
          # If one is expired the element is removed from
          # the administration.
          @@jobs.each { "XXX" }
        rescue Exception
          @logger.error "Cleanup thread error: #{$!}"
        end
      end
    end
  end

end
```

When I position my cursor on "XXX" I get the following error:

<pre>
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/Users/fred/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "RubyBlockConverter in /Users/fred/Library/Application Support/Sublime Text 3/Installed Packages/Ruby Block Converter.sublime-package", line 75, in run
  File "RubyBlockConverter in /Users/fred/Library/Application Support/Sublime Text 3/Installed Packages/Ruby Block Converter.sublime-package", line 42, in match_blocks
  File "X/tokenize.py", line 544, in _tokenize
  File "<tokenize>", line 6
    end
    ^
IndentationError: unindent does not match any outer indentation level
</pre>

The problem is the line `p @@jobs` or the line `raise ParseException.new 403, "busy" etc.`. If I remove either of those lines the block converter will work properly. I sometimes put temporary print statements all the way to the left to make them stick out. It is odd that a block that is converted is bothered by indentation in another method.

Hopefully you have enough information to address this.

**Comment by irohiroki** [comment]
unfortunately this error is in a sublime text built-in library, not mine. my plugin strongly relies on the built-in parser, which is not perfect. at least we can appeal to Sublime Text official about the issue.
