### ISSUE TITLE
Add ST3 tag to package control

### ISSUE THREAD

**Issue by dsandstrom** [irohiroki/RubyBlockConverter#9]
Can you add the "ST3" tag to [package control](https://sublime.wbond.net/packages/Ruby%20Block%20Converter) so it can be installed onto that version?  There has been changes to package control and it is smart to know if you are trying to install a package to sublime 2 or 3.  I think that needs to be set in order to install it though package control (Package Control: Install Package).  In the mean time, It can still be installed by adding your repo (https://github.com/irohiroki/RubyBlockConverter) first.

**Comment by irohiroki** [comment]
ok, but I'm still not sure what the tag on that page is or how I can install my package to ST3 via package control. maybe I need to study a bit and I'm willing to manage to fix this issue. thanks for informimg me.

**Comment by dsandstrom** [comment]
Ya, it's just a minor thing.  You probably have to tell Will Bond somehow.

How to install: ctrl+shift+p, type "install", then type the package name (it might be different for you if you're using a different language.

Or you can install any package with a repo url: type "repo" instead of install, add repo url.  Then you can install like above.

**Comment by irohiroki** [comment]
RubyBlockConverter now appears in the available plugin list. all I have to do was to send a pull req to wbond/package_control_channel.

**Comment by dsandstrom** [comment]
Thanks.  That makes sense now.
